yumcha_website:
    resource: "@YumchaWebsiteBundle/Controller/"
    type:     annotation
    prefix:   /

login_check:
    pattern:   /admin/login_check
    options:
      i18n: false

admin_logout:
    pattern:   /admin/logout
    options:
      i18n: false