<?php

namespace Yumcha\Bundle\WebsiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BubbleIngredientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BubbleIngredientRepository extends EntityRepository
{
}
