<?php

namespace Yumcha\Bundle\WebsiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BubbleIngredientCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BubbleIngredientCategoryRepository extends EntityRepository
{
}
