<?php

namespace Yumcha\Bundle\WebsiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * IcecreamCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IcecreamCategoryRepository extends EntityRepository
{
}
