<?php

namespace Yumcha\Bundle\WebsiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * IcecreamFlavourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IcecreamFlavourRepository extends EntityRepository
{
    public function getFlavoursAndCategories()
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $query = $qb->select('f, c')
            ->from('YumchaWebsiteBundle:IcecreamFlavour', 'f')
            ->innerJoin('f.category', 'c')
            ->orderBy('c.id')
        ;

        return $query->getQuery()->getResult();
    }
}
